<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Settlement extends Model
{
    protected $fillable=['name','zip_code'];
    protected $hidden = ['id', 'municipality_id', 'zone_type_id', 'settlement_type_id', 'zip_code', 'created_at', 'updated_at'];

    //

    public function municipality()
    {
        return $this->belongsTo(Municipality::class);
    }

    public function zoneType()
    {
        return $this->belongsTo(ZoneType::class);
    }

    public function settlementType()
    {
        return $this->belongsTo(SettlementType::class);
    }

    public function toArray()
    {
        $data = parent::toArray(); // TODO: Change the autogenerated stub
        $data['key'] = $this->id;
        $data['zone_type'] = $this->zoneType->name;
        $data['settlement_type'] = $this->settlementType->toArray();
        return $data;
    }
}
